disabled_rules:
  - trailing_whitespace
  - identifier_name
  - file_length
  - type_body_length
  - function_body_length
  - function_parameter_count
  - force_cast
  - force_try
  - line_length
  - cyclomatic_complexity
  - type_name

included:
  - StudyApp

excluded:
  - Pods
  - Carthage
  - DerivedData

opt_in_rules:
  - force_unwrapping

